name = "kaalveniiz-analytics"
main = "src/worker.js"
compatibility_date = "2026-05-24"

[vars]
ALLOWED_ORIGINS = "https://kaalveniiz.net,https://www.kaalveniiz.net,https://kaalveniiz.github.io"
CLOUDFLARE_ZONE_ID = ""

[triggers]
crons = ["15 16 * * *"]

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "kaalveniiz_analytics"
database_id = "215baff3-8d6b-4cdf-8472-16142f86f2c0"
