baseURL = "https://kaalveniiz.github.io/"
locale = "en-US"
title = "kaalveniiz.blog"
disableKinds = ["rss"]
relativeURLs = false

[params]
  description = "Unicode-style personal blog"
  analytics_endpoint = ""

[permalinks]
  posts = "/posts/:slug/"

[taxonomies]
  tag = "tags"
