baseURL = "https://kaalveniiz.github.io/"
languageCode = "en-us"
title = "HALPHAS KREUZ.blog"

[params]
  description = "Unicode-style personal blog"

[permalinks]
  posts = "/posts/:slug/"

[taxonomies]
  tag = "tags"

disableKinds = ["rss"]

relativeURLs = true
